#!/usr/bin/env bash
#
# Clean and prepare the system a la virt-sysprep
#
# See:
# http://libguestfs.org/virt-sysprep.1.html and
# https://github.com/libguestfs/libguestfs/tree/master/sysprep

# Packer logging
echo "Running requested virt-sysprep style operations..."

# Set an explict path to Bash executable to ensure our scripts run under
# bash exclusively. Note that running the 'sh' command on Debian and
# Ubuntu systems will actually start a dash shell. dash will error and
# cause us problems when it encounters bash specific commands in the
# scripts
SH="$(command -v bash)"
if [ "x${SH}" = "x" ]; then
    echo "ERROR: Could not enumerate path for bash executable. Exiting"
    exit -1
fi
# Get the path to the location of the sysprep scripts
PREFIX="$PACKER_DIR/packer-virt-sysprep"

# bash_history: Remove all users bash history. Remove:
#     * /home/*/.bash_history
#     * /root/.bash_history
if [ "$SYSPREP_OP_BASH_HISTORY" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprepL-op-bash-history.sh"
    ${SH} ${PREFIX}/sysprep-op-bash-history.sh
fi

# crash_data: Remove crash data generated by kexec-tools by removing:
#     * /var/crash/*
#     * /var/log/dump/*
if [ "$SYSPREP_OP_CRASH_DATA" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-crash-data.sh"
    ${SH} ${PREFIX}/sysprep-op-crash-data.sh
fi


# dhcp-client-state: Remove DHCP client release by removing:
#     * /var/lib/dhclient/*
#     * /var/lib/dhcp/*
if [ "$SYSPREP_OP_DHCP_CLIENT_STATE" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-dhcp-client-state.sh"
    ${SH} ${PREFIX}/sysprep-op-dhcp-client-state.sh
fi

# firewall-rules: Remove custom firewall rules by removing:
#     * /etc/sysconfig/iptables
#     * /etc/firewalld/services/*
#     * /etc/firewalld/zones/*
if [ "$SYSPREP_OP_FIREWALL_RULES" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-firewall-rules.sh"
    ${SH} ${PREFIX}/sysprep-op-firewall-rules.sh
fi

# logfiles: Remove every logfile ever created by removing:
#     # ...a ton of stuff!
if [ "$SYSPREP_OP_LOGFILES" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-logfiles.sh"
fi

# machine-id: Remove the local machine ID by removing content from:
#     * /etc/machine-id
#     * /var/lib/dbus/machine-id
if [ "$SYSPREP_OP_MACHINE_ID" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-machine-id.sh"
    ${SH} ${PREFIX}/sysprep-op-machine-id.sh
fi

# mail-spool: Remove email from the local mail spool directory
#     # /var/spool/mail/*
#     * /var/mail/*
if [ "$SYSPREP_OP_MAIL_SPOOL" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-mail-spool.sh"
    ${SH} ${PREFIX}/sysprep-op-mail-spool.sh
fi

# package-manager-cache: Remove package manager cache by removing files
# under:
#     * /var/cache/apt/archives/
#     * /var/cache/dnf/
#     * /var/cache/yum/
#     * /var/cache/zypp*
if [ "$SYSPREP_OP_PACKAGE_MANAGER_CACHE" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-package-manager-cache.sh"
    ${SH} ${PREFIX}/sysprep-op-package-manager-cache.sh
fi

# rpm-db: Remove host-specific RPM database files by removing:
#     # /var/lib/rpm/__db.*
if [ "$SYSPREP_OP_RPM_DB" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-rpm-db.sh"
    ${SH} ${PREFIX}/sysprep-op-rpm-db.sh
fi

# ssh-hostkeys: Remove the SSH host keys in the guest by removing:
#     * /etc/ssh/*_host_*
if [ "$SYSPREP_OP_SSH_HOSTKEYS" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-ssh-hostkeys.sh"
    ${SH} ${PREFIX}/sysprep-op-ssh-hostkeys.sh
fi

# tmp-files: Remove all temporary files and directories by removing:
#     * /tmp/*
#     * /var/tmp/*
if [ "$SYSPREP_OP_TMP_FILES" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-tmp-files.sh"
    ${SH} ${PREFIX}/sysprep-op-tmp-files.sh
fi

# yum-uuid: Remove the yum UUID
#     * /var/lib/yum/uuid
if [ "$SYSPREP_OP_YUM_UUID" = true ]; then
    echo -e "\tRunning ${PREFIX}/sysprep-op-yum-uuid.sh"
    ${SH} ${PREFIX}/sysprep-op-yum-uuid.sh
fi
